import { join } from 'node:path';
import {
  ExitCode,
  type Command,
  type CommandContext,
  type CommandResult,
  type Diagnostic,
} from '../command.js';

/** A file to be written during bootstrap. */
export interface TemplateFile {
  readonly path: string;
  readonly content: string;
}

/** A named project template. */
export interface Template {
  readonly name: string;
  readonly files: readonly TemplateFile[];
}

/** A write-only, existence-aware file sink so bootstrap is testable and non-destructive. */
export interface FileSink {
  exists(path: string): boolean;
  write(path: string, content: string): void;
}

/** Dependencies for the `init` command. */
export interface InitDeps {
  readonly fs: FileSink;
  readonly templates: ReadonlyMap<string, Template>;
  /** The base directory bootstrapped when `--dir` is omitted. */
  readonly cwd: string;
}

/** The manifest generated by `init`. */
export interface GeneratedManifest {
  readonly name: string;
  readonly template: string;
}

/** Validate a generated manifest. Returns the list of issues (empty when valid). */
export function validateManifest(manifest: GeneratedManifest): string[] {
  const issues: string[] = [];
  if (manifest.name.trim() === '') {
    issues.push('manifest "name" must not be empty');
  }
  if (manifest.template.trim() === '') {
    issues.push('manifest "template" must not be empty');
  }
  return issues;
}

const MANIFEST_FILENAME = 'helix.config.json';

function readString(flags: CommandContext['flags'], key: string): string | undefined {
  const value = flags[key];
  return typeof value === 'string' ? value : undefined;
}

/**
 * `helix init` — bootstrap a repository from a template. The command is strictly
 * non-destructive: if any target file already exists it writes nothing and
 * fails. The generated manifest is validated after generation, and a
 * success result reports exactly the files created (Constitution Article 7).
 */
export function createInitCommand(deps: InitDeps): Command {
  return {
    name: 'init',
    description: 'bootstrap a new Helix repository from a template',
    run(context: CommandContext): CommandResult {
      const name = readString(context.flags, 'name') ?? '';
      const templateName = readString(context.flags, 'template') ?? 'minimal';
      const dir = readString(context.flags, 'dir') ?? deps.cwd;

      const template = deps.templates.get(templateName);
      if (template === undefined) {
        const available = [...deps.templates.keys()].sort().join(', ');
        return {
          exitCode: ExitCode.usage,
          diagnostics: [
            {
              severity: 'error',
              code: 'INIT_UNKNOWN_TEMPLATE',
              message: `unknown template "${templateName}"; available: ${available || '(none)'}`,
            },
          ],
        };
      }

      const manifest: GeneratedManifest = { name, template: templateName };
      const manifestIssues = validateManifest(manifest);
      if (manifestIssues.length > 0) {
        return {
          exitCode: ExitCode.usage,
          diagnostics: manifestIssues.map((message): Diagnostic => ({
            severity: 'error',
            code: 'INIT_INVALID_MANIFEST',
            message,
          })),
        };
      }

      const files: TemplateFile[] = [
        ...template.files,
        { path: MANIFEST_FILENAME, content: `${JSON.stringify(manifest, null, 2)}\n` },
      ];
      const targets = files.map((file) => ({ ...file, target: join(dir, file.path) }));

      const conflicts = targets.filter((file) => deps.fs.exists(file.target));
      if (conflicts.length > 0) {
        return {
          exitCode: ExitCode.error,
          diagnostics: conflicts.map((file): Diagnostic => ({
            severity: 'error',
            code: 'INIT_FILE_EXISTS',
            message: `refusing to overwrite existing file "${file.target}"`,
          })),
        };
      }

      for (const file of targets) {
        deps.fs.write(file.target, file.content);
      }

      return {
        exitCode: ExitCode.success,
        output: { created: targets.map((file) => file.target) },
      };
    },
  };
}
